### ISSUE TITLE
SEO: canonical links for "typed"

### ISSUE THREAD

**Issue by TimMoore** [akka/akka.io#618]
Despite the addition of canonical links to pages on doc.akka.io, I still frequently see outdated search results. For example, try an incognito [search for "akka typed"](https://www.google.com/search?q=akka+typed). Currently, the first, highlighted result points to https://doc.akka.io/docs/akka/2.5.4/scala/typed-actors.html

That page contains this canonical link:

```html
<link rel="canonical" href="https://doc.akka.io/docs/akka/current/scala/typed-actors.html"/>
```

The URL https://doc.akka.io/docs/akka/current/scala/typed-actors.html redirects to https://doc.akka.io/docs/akka/current/typed-actors.html?language=scala. My suspicion is that Google penalizes canonical links that redirect.

# References

- https://moz.com/learn/seo/canonicalization recommends against this kind of "mixed signals".
- https://sitebulb.com/hints/indexability/canonical-hints/canonical-points-to-a-redirecting-url/ says that in this case, search engines "will ignore the canonicals entirely and try to make their own decisions about what 'the canonical URL' should be"

**Comment by ennru** [comment]
That in particular must be a result of the old way of separating Scala and Java in the URLs. The redirect happens as we nowadays use the `language` attribute. 
I can get the `sed` sword out and rewrite those in the older Akka 2.5 docs so that there is no redirect.

The Google Search console shows if they accepted the canonical URL. In this case it shows as if it **didn't see the canonical at all**, even though it scanned just yesterday.

**Comment by ennru** [comment]
The canonical URL now shows in the Google search console.
But an issue with the "typed" docs is that the URL changed a bit over time:
- `/typed-actors.html`
- `/scala/typed.html`
- `/typed/index.html` (current)

So the different canonicals in there might make Google believe these are different pages 
![bild](https://user-images.githubusercontent.com/458526/60162738-6f833a00-97fa-11e9-9470-5af5bda40fe1.png)

**Comment by TimMoore** [comment]
Just tried the search (incognito) again:

- https://doc.akka.io/docs/akka/current/typed/index.html appears first. Good!
- Second result is https://akka.io/blog/2017/05/05/typed-intro. A nice, popular post, but we might want to add an update to the top, pointing people to more up-to-date sources.
- https://doc.akka.io/docs/akka/2.5.4/scala/typed.html
- https://doc.akka.io/docs/akka/2.5.3/scala/typed.html
- https://doc.akka.io/docs/akka/2.5.21//typed/

The last of these shows the "outdated version" banner, but the others don't (I think it was added back to the docs after they were published).

The canonical links for 2.5.3 and 2.5.4 use the old structure. I don't know why 2.5.21 shows up separately.

**Comment by ennru** [comment]
An interesting detail which shows in my earlier results as well is the double-slash in the URL for 2.5.21. 
The Google Search Console states that `https://doc.akka.io/docs/akka/2.5.21//typed/` is not on Google, but it is still in the search results?!

**Comment by TimMoore** [comment]
I requested a reindex of the page yesterday, and that seems to have helped. At the time it was showing that it _was_ in the index, with no canonical selected. Right now, it's showing not in the index, user-declared canonical is still "none" for some reason, but Google-selected canonical is correctly set to https://doc.akka.io/docs/akka/current/typed/index.html.

It still shows in search results for me, but maybe it's an eventual consistency issue? I'll try again in a few days.

It would still be nice to do something about the older versions. I guess the problem is that the canonical links are generated via a simple substitution? Would we be able to add special case exceptions? I don't love the idea of complicating it too much, but it would be nice if we could clear them out somehow.

Alternatively, would we be able to retroactively apply the "outdated version" banner?

**Comment by raboof** [comment]
> user-declared canonical is still "none" for some reason

You mean for https://doc.akka.io/docs/akka/2.5.21//typed/? 

> It would still be nice to do something about the older versions. I guess the problem is that the canonical links are generated via a simple substitution?

We've been back-fixing a lot of canonicals in old pages manually (well, with sed), I think that's reasonable.

> Alternatively, would we be able to retroactively apply the "outdated version" banner?

That seems harder and not as nice.

**Comment by ennru** [comment]
I've now rewritten the canonical URL for `typed.html` in Akka 2.5.0 to 2.5.6 docs to point to `current/typed/index.html`.

**Comment by TimMoore** [comment]
Thanks, @ennru! I requested a reindex of https://doc.akka.io/docs/akka/2.5.4/scala/typed.html so we can see if that takes effect once it completes.

**Comment by TimMoore** [comment]
Good news and bad news:

Bad news first: now when I do an incognito search for akka typed, the first thing on the page is a ["featured snippet"](https://support.google.com/websearch/answer/9351707) that says "Akka Typed Actors is an implementation of the Active Objects pattern." and links to https://doc.akka.io/docs/akka/current/typed-actors.html. This is strange, because that page is rather low in the search results, and (good news) the first search result is still correctly returning https://doc.akka.io/docs/akka/current/typed/index.html.

It doesn't seem like you can do much to control featured snippets other than [opt out](https://support.google.com/webmasters/answer/6229325). Maybe we should.

Here are the rest of the top few results:

- https://akka.io/blog/2017/05/05/typed-intro
- https://doc.akka.io/docs/akka/2.5.8/typed.html
- https://doc.akka.io/docs/akka/2.5.3/scala/typed.html
- https://doc.akka.io/docs/akka/current/typed-actors.html
- https://www.lightbend.com/blog/akka-2-5-22-brings-akka-typed-to-production-ready

So, the improvement is that the 2.5.4, 2.5.3, and 2.5.21 links no longer appear, but for some reason the 2.5.8 and 2.5.3 ones still do. Their canonical tags look right to me, but the Google search console is still reporting their "User-declared canonical" as "None". The same is true for the 2.5.4 page that is no longer returned on the first page (at least). 🤷‍♂ 

https://akka.io/blog/2017/05/05/typed-intro still has a high ranking, but is outdated.

**Comment by raboof** [comment]
> https://doc.akka.io/docs/akka/current/typed-actors.html

That page disappears (redirects to the migration guide) in 2.6, so perhaps that will 'naturally' drop off then?

> 2.5.8 and 2.5.3 ones still do. Their canonical tags look right to me, but the Google search console is still reporting their "User-declared canonical" as "None".

I've seen that before as well and couldn't quite explain it.

One thing I noticed (though I don't have 'hard evidence' yet) is that Google seems to dislike 'index.html' in URL's. Perhaps it will help to link to https://doc.akka.io/docs/akka/current/typed/ instead of https://doc.akka.io/docs/akka/current/typed/index.html ? I started on this in paradox at https://github.com/lightbend/paradox/pull/335 (it seems a little nicer even if it turns out Google doesn't reward it after all), but marked that PR "Draft" since I haven't actually tested it yet.

> https://akka.io/blog/2017/05/05/typed-intro

perhaps we should add an infobox to the beginning of that blog post explaining that and linking to the docs.

**Comment by raboof** [comment]
> Google seems to dislike 'index.html' in URL's

I've also seen instances where Google *did* see the 'User-selected canonical' but still chose a different one. This was also when the user-selected canonical contained 'index.html'.

**Comment by raboof** [comment]
> the first thing on the page is a "featured snippet" that says "Akka Typed Actors is an implementation of the Active Objects pattern." and links to https://doc.akka.io/docs/akka/current/typed-actors.html

Added https://github.com/akka/akka/pull/27343

**Comment by ennru** [comment]
Just tried the Google search -- I think this is good enough now.

![bild](https://user-images.githubusercontent.com/458526/93885415-670efd00-fce4-11ea-97a6-305c5eefa64f.png)
