### ISSUE TITLE
Make the version in Paradox clickable to see available versions

### ISSUE THREAD

**Issue by ennru** [akka/akka.io#654]
Akka and other modules don't have a page listing prior versions. It would make sense to have that and link it from the version number in the docs

![image](https://user-images.githubusercontent.com/458526/70317507-307ff880-181e-11ea-8a6a-7ab6df504c90.png)

Other project have such a thing:

[Scala](https://www.scala-lang.org/download/all.html)
[Play](https://www.playframework.com/releases)
[Lagom](https://www.lagomframework.com/documentation/)

**Comment by johanandren** [comment]
We do though: https://akka.io/docs/other-releases.html

We just didn't want to put emphasis on that page.

**Comment by patriknw** [comment]
I’m also not sure what the purpose would be. Maybe useful to switch between different minor versions, but not for patch versions.
