### ISSUE TITLE
Java API doc links from modules not working

### ISSUE THREAD

**Issue by johanandren** [akka/akka.io#679]
For example streams: https://doc.akka.io/japi/akka/current/index.html?akka/stream/package-summary.html go to some general package overview. Should be https://doc.akka.io/japi/akka/current/akka/stream/package-summary.html

**Comment by ennru** [comment]
That is the Javadoc frames vs not-frames thing. We started opting out of frames recently.
https://github.com/akka/akka/pull/28180/files#diff-24b02a4e7c124bb4fa1faf04ae3de66f
