### ISSUE TITLE
Update docs module page

### ISSUE THREAD

**Issue by johanandren** [akka/akka.io#710]
When it was first conceived the purpose of the docs page was to be a stepping stone into each of the major modules of Akka. It has since kind of outgrown that, listing some of the projects in the Akka umbrella but not all. I think that the box-format also does not work great when the types of modules has changed beyond the initial scope. 

I don't have a concrete design idea but I think we should redesign it into some form of categories with subsection and also cover the persistence plugins and perhaps also list sample repos.

WDYT?

**Comment by ennru** [comment]
Done with
- #901
