### ISSUE TITLE
Version warnings for Akka and Akka HTTP

### ISSUE THREAD

**Issue by ennru** [akka/akka.io#737]
The version warnings for patches and old minor versions need to be revived.

No warnings show for old patches
- https://doc.akka.io/docs/akka/2.5.30/
- https://doc.akka.io/docs/akka-http/10.1.11/

For the latest patch of an old minor version, we should show it as an information (rather than "not supported anymore")
- https://doc.akka.io/docs/akka/2.5/
- https://doc.akka.io/docs/akka-http/10.1/

**Comment by ennru** [comment]
Even seen in https://github.com/akka/alpakka-kafka/pull/1202

**Comment by raboof** [comment]
> No warnings show for old patches
> 
>     * https://doc.akka.io/docs/akka/2.5.30/
> 
>     * https://doc.akka.io/docs/akka-http/10.1.11/

These seem to work for me?

> For the latest patch of an old minor version, we should show it as an information (rather than "not supported anymore")
> 
>     * https://doc.akka.io/docs/akka/2.5/
> 
>     * https://doc.akka.io/docs/akka-http/10.1/

We reworded this to 'outdated', which seems to fix this concern?

I think we can close this issue, or is there anything left to do here?

**Comment by ennru** [comment]
You are right. All good now.
