### ISSUE TITLE
Add Akka Projections to the docs overview page

### ISSUE THREAD

**Issue by raboof** [akka/akka.io#749]
Related: #408, https://github.com/akka/akka/issues/29710

**Comment by nitikagarw** [comment]
@raboof Can I pick this issue? Looks like we need to add a `div` [here](https://github.com/akka/akka.io/blob/master/docs/index.html#L61)

**Comment by raboof** [comment]
@nitikagarw sure, thanks!

**Comment by patriknw** [comment]
We already have a grid of 3x4. Can we remove one to avoid another row? I think we can remove Akka Enhancements since the most important pieces are open sourced now. Then place Akka Projections after Akka Persistence.

**Comment by nitikagarw** [comment]
@raboof @patriknw So do we want to remove `Akka Enhancements`. or I should add another row?

**Comment by patriknw** [comment]
@nitikagarw please remove Akka Enhancements

**Comment by nitikagarw** [comment]
I have opened a PR: https://github.com/akka/akka.io/pull/765
