### ISSUE TITLE
Documentation pages have been broken for several hours

### ISSUE THREAD

**Issue by danellis** [akka/akka.io#755]
Pages such as https://doc.akka.io/docs/akka-http/current/client-side/index.html/ and https://doc.akka.io/docs/akka/current/typed/index.html/ are returning a 404, while some pages, such as https://doc.akka.io/docs/akka-http/current/introduction.html, are fine.

**Comment by danellis** [comment]
Okay, it looks like at some point the `index.html` files served up a *permanent* redirect to `index.html/`, so they have been cached. The pages load okay with cache disabled. Perhaps some change needs to be made to ensure this doesn't happen again?

**Comment by ennru** [comment]
Thank you for reporting it here.
We have a discussion in https://discuss.lightbend.com/t/unable-to-access-akka-documentation-server-seems-to-be-down-and-have-a-config-issue/7375 as well.

**Comment by ennru** [comment]
To get the permanent redirects out of browser caches I've added another redirect from some `.../index.html/` to just `.../`.
