### ISSUE TITLE
remove disqus?

### ISSUE THREAD

**Issue by raboof** [akka/akka.io#794]
seems old-fashioned, perhaps replace it with a link to https://akka.io/get-involved/ ?

**Comment by patriknw** [comment]
Do you mean the "Discuss Akka forums" link in the footer or is the suggestion to remove the entire forum?

**Comment by raboof** [comment]
I mean the 'comment section' below articles

![disqus](https://user-images.githubusercontent.com/131856/119827781-cec3ba80-bef9-11eb-94ad-c3a8eadbde55.png)

**Comment by patriknw** [comment]
ok, 👍 
sounds good, we don't want discussion there anyway
