### ISSUE TITLE
Old version warning states that 2.6 is not supported

### ISSUE THREAD

**Issue by patriknw** [akka/akka.io#865]
Have we always had a warning like that for previous (still supported) version or have we misconfigured the versions?

<img width="1084" alt="Screenshot 2022-11-25 at 08 46 39" src="https://user-images.githubusercontent.com/336161/203928201-9f9754fd-84ec-4d65-99de-926a64cdb7ca.png">

**Comment by ennru** [comment]
There is some smart logic behind it... let me try to remember.

**Comment by ennru** [comment]
The data feeding the warning is in https://akka.io/versions.json
I removed the `outdated` flag for Akka 2.6 and Akka HTTP 10.2.

Browser caching aside and it should not show anymore.
